### PR TITLE
ticket 2 hover effect

### PR DESCRIPTION
**Pull request by Shimaadnan**

### CODE REVIEW

**Review by LloydRivers — CHANGES_REQUESTED** [review]
Your build tests have failed.

Don't forget to run "yarn lint" and check for linting errors.

**Comment by j4ck-wright** [comment]
This is an interesting one - think you might want to disable max line length if you wanna use Tailwind

**Comment by LloydRivers** [comment]
> This is an interesting one - think you might want to disable max line length if you wanna use Tailwind

@j4ck-wright I agree.

**Review by LloydRivers — APPROVED** [review]
@Shimaadnan 

Always run yarn lint and test on your local branch.

Check the files changed, you will see 16K plus changes. This is telling us we dont have prettier configured the same.

If you want, look into [this](https://prettier.io/docs/en/configuration.html)

Create a brand, fix the prettier stuff and make a PR, if you need help give me a shout.

**Pull request merged**
